default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: 123123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_portion_development

test:
  <<: *default
  database: api_portion_test

production:
  <<: *default
  database: api_portion_production
  username: api_portion
  password: <%= ENV["API_PORTION_DATABASE_PASSWORD"] %>
